version: '1.0'

services:
  web:
    build: .
    ports:
      - 8888:8888
    depends_on:
      - db
      - nginx
      - redis
  db:
    image: mysql:5.7
  nginx:
    image: nginx:1.17
  redis:
    image: redis:5.0.8

# 可选
#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080