version: '1.0'

services:
  web:
    build: .
    container_name: web
    volumes:
      - ../logs/err.log: /code/log/gunicorn.log
    depends_on:
      - db
  #      - redis
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=mx/58MFuLJ6^%.q
    volumes:
      - ./config/mysql/test_post.sql:/docker-entrypoint-initdb.d/init.sql
  nginx:
    image: nginx:1.17
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    ports:
      - 8888:80
#  redis:
#    image: redis:5.0.8

# 可选
#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080